refactoring - application, baseWriter
keboola/db-writer-common pull request #47
Opened 2023-10-22 14:53 UTC by ondrajodas

2024-02-08 12:05 UTC, AdamVyborny reviewed
Zase jen pár drobností...

2024-02-08 20:59 UTC, ondrajodas commented on src/Writer/BaseWriter.php
> +    protected function writeIncremental(ExportConfig $exportConfig): void
pokud na tom nelpíš tak bych to tak nechal... v tomhle případě mi to příjde i celkem přehledné

2024-02-08 21:02 UTC, ondrajodas commented on composer.json
> +    "keboola/csv": "^4.0",
teď koukám že to je sice jen v dev, ale aspoň budou i testy s očekávaným výstupem

2024-02-08 21:16 UTC, ondrajodas commented on src/Validator.php
> +    public function validateTableItems(string $tablePath, array $items): array
jo pravda - fixnuto

2024-02-09 12:39 UTC, AdamVyborny requested changes
Ještě ten composer.phar v README asi už není aktuální, ne?

2024-02-09 12:44 UTC, ondrajodas commented
jo trochu jsem to přepsal to README

2024-02-09 20:26 UTC, merged